/* ============================================================
   PHIL McDARBY — WORKS DATA (single source of truth)
   One entry per artwork. Imagery stripped from the previous
   philmcdarby.com site (1200px 'large' versions where the old
   site offered them, display size otherwise). When Phil's
   master files arrive, drop them into img/ under the same
   slug filenames and update w/h — nothing else changes.
   ============================================================ */

const PRINT_SIZES = ['A3', 'A2', 'A1', 'Large format / custom'];

const COLLECTIONS = {
  'digital-art': 'Digital Art',
  'photography': 'Photography',
};

const WORKS = [
  {
    slug: "the-amber-dragons-hoard",
    title: "The Amber Dragon’s Hoard",
    collection: "digital-art",
    image: "img/the-amber-dragons-hoard.jpg",
    w: 1200, h: 877,
    featured: true,
    note: "I created the Amber Dragon a good while ago, and have spent a long time trying to create the perfect environment for him.  I think I’ve started this image about 10 times at this stage! As with all my Wood Dragons, he is created in Photoshop, a combination of digital painting and elements of my own photography for texture. He is called the Amber Dragon as I based his eye on that wonderful golden substance. The original res is 9500px wide (it would print around 3 metres wide).\n\nThe Robin is painted/textured using a combination of Robin references – I took some liberties with the eye/beak area as I discovered through the process that it’s quite difficult to make a bird look like it’s ‘looking’ at something – the lack of pupil is tricky! The Ant has spotted an opportunity and is making the most of the distracted Dragon.The background is a combination of painting and elements of my own shots - I was trying to capture a hint of faery architecture without overdoing it.",
  },
  {
    slug: "a-dance-of-light",
    title: "A Dance of Light",
    collection: "digital-art",
    image: "img/a-dance-of-light.jpg",
    w: 1602, h: 941,
    featured: true,
    note: "This was a bit of a labour of love - and an experiment in time management! My full-time job and a looong commute means I have very little time to do personal work.That’s why my site has looked the same for three years! I decided to try to create an image in tiny increments - chipping away at this, half an hour here and there, for over three months.\n\nIt was great to get back into it, continuing work on my book, The World of the Wood Dragon.\n\nI also wanted to see what this looked like printed on metal - I was chuffed with the results.",
  },
  {
    slug: "the-wood-dragon-the-cricket",
    title: "The Wood Dragon & The Cricket",
    collection: "digital-art",
    image: "img/the-wood-dragon-the-cricket.jpg",
    w: 760, h: 386,
    featured: true,
    note: "Created in Photoshop, using a Wacom Tablet and my own macro shots.",
  },
  {
    slug: "the-moss-dragon-at-amberfall",
    title: "The Moss Dragon at Amberfall",
    collection: "digital-art",
    image: "img/the-moss-dragon-at-amberfall.jpg",
    w: 1400, h: 752,
    note: "This image was created in Photoshop, and is a ‘older’ version of the Moss Dragon who encountered the butterfly. I decided subsequently to keep all species of Wood Dragon at a micro level, but I liked the atmosphere in this image so decided to include it. The Robin is the Moss Dragon’s familiar, whose nest is built into the dragon’s back.\n\nA detailed workshop on this image was created for Issue 54 of Advanced Photoshop.",
  },
  {
    slug: "auri",
    title: "Auri",
    collection: "digital-art",
    image: "img/auri.jpg",
    w: 1200, h: 1662,
    featured: true,
    note: "I love the world Pat Rothfuss has created in the Kingkiller Chronicle, and I keep coming back to it whenever I get a moment to do personal work. This is Auri, surveying her domain. The Underthing is a vast, sprawling ruin under the University - a remnant of an ancient civilisation, a mystery (at least I think it is!). Pat is releasing a novella this October (2014) set in Auri’s world, called The Slow Regard of Silent Things. If the Name of the Wind and The Wise Man’s Fear are anything to go by, it will be incredible.\n\nI started this image a long time ago. I began by modelling the Underthing in Maya, creating random pillars and balconies and stairways. I hung the environment in a mirror box so the reflections would create a sense of vastness, and used that basic render to begin painting. I’ve used a few abandoned factory elements as reference, heavily painted. Auri’s hair is always described in a very particular way, so my daughter Ava kindly stood with the sun shining through hers to give me reference for the painting.\n\nAs always it’s a lot bigger than it probably needs to be - this would print a couple of metres wide no problem.",
  },
  {
    slug: "heart-of-the-glade",
    title: "Heart Of The Glade",
    collection: "digital-art",
    image: "img/heart-of-the-glade.jpg",
    w: 568, h: 795,
    featured: true,
    note: "Created in Maya, Bryce, Poser & Photoshop.",
  },
  {
    slug: "the-green-man-awakens",
    title: "The Green Man Awakens",
    collection: "digital-art",
    image: "img/the-green-man-awakens.jpg",
    w: 900, h: 1107,
    featured: true,
    note: "Created in Photohop over about 6 weeks - a combination of digital painting and elements of my own photography.\n\nA detailed breakdown of the process can be found here, and the original Landscape format image is here.",
  },
  {
    slug: "an-encounter-at-greenspindle",
    title: "An Encounter at Greenspindle",
    collection: "digital-art",
    image: "img/an-encounter-at-greenspindle.jpg",
    w: 1600, h: 1000,
    note: "I always seem to start these things by describing how long it took to finish the image, so in the interest of keeping up tradition….this one took a year and a half! In fairness, it was done in dribs and drabs – I started Greenspindle, the tiny citadel, way back in October 2008. I’ve been revisiting it every now and again, adding doors, windows, levels etc as I went along. As always, the image is a mixture of many hours of painting, 100’s of layers, and elements of my own photography. The Apple Dragon (spawned from an apple tree) is my most recent Wood Dragon species (I have about 12 now), and I’ve been working on him for the last couple of weeks. The Fire Fairy was painted using a lot of Blur’s ‘GoodBrush’ set – thanks to him for making them freely available. This is a greeting between the two creatures, both weaving the magic of the wood.\nThe image ended up being nearly 17,000 pixels across before cropping, definitely the biggest I’ve ever worked on. The saves were a gig and half each time and my poor PC took a pounding!",
  },
  {
    slug: "faerieholme",
    title: "Faerieholme",
    collection: "digital-art",
    image: "img/faerieholme.jpg",
    w: 568, h: 757,
    note: "Created in Photoshop.",
  },
  {
    slug: "luring-the-draccus",
    title: "Luring The Draccus",
    collection: "digital-art",
    image: "img/luring-the-draccus.jpg",
    w: 1393, h: 755,
    note: "This image was a kind of self-imposed challenge – I totally fell in love with an incredible book called The Name Of The Wind by Patrick Rothfuss, and as a tribute, I wanted to try and recreate a scene from the book. Usually my images evolve as I work on them, often ending up only vaguely resembling the original idea, but with this, I set myself a very specific brief – Pat’s amazing words – and set about trying to make it real. It was a really challenging exercise, and I loved doing it. Took about 2 weeks of my spare time I think.\n\nAs always, there is a mixture of a ton of painting and my own shots – the Draccus is painted from scratch, referencing various beasties from hippos to rhinos to monitor lizards. The way the creature is described is quite simple, there’s nothing particularly ‘dragon-like’ about it, no unnecessary adornments etc – just a giant armour-plated herbivore lizard who breathes crackling blue fire. I don’t want to spoil the scene at all, so I’ll leave the interpretation up to you guys - I cannot recommend this stunning book enough!",
  },
  {
    slug: "caamora",
    title: "Caamora",
    collection: "digital-art",
    image: "img/caamora.jpg",
    w: 568, h: 757,
    note: "Created in Bryce, Maya & Photoshop.\nCommissioned by Dave Eberly for Geometric Tools.",
  },
  {
    slug: "dryad",
    title: "Dryad",
    collection: "digital-art",
    image: "img/dryad.jpg",
    w: 568, h: 757,
    note: "Created using ZBrush & Photoshop.",
  },
  {
    slug: "dwelling",
    title: "Dwelling",
    collection: "digital-art",
    image: "img/dwelling.jpg",
    w: 568, h: 757,
    note: "Created using ZBrush & Photoshop.",
  },
  {
    slug: "elemend",
    title: "Elemend",
    collection: "digital-art",
    image: "img/elemend.jpg",
    w: 568, h: 757,
    note: "Created using ZBrush & Photoshop.",
  },
  {
    slug: "exiles-return",
    title: "Exile’s Return",
    collection: "digital-art",
    image: "img/exiles-return.jpg",
    w: 568, h: 863,
    note: "Created using ZBrush, Maya, Bryce & Photoshop.",
  },
  {
    slug: "fathom",
    title: "Fathom",
    collection: "digital-art",
    image: "img/fathom.jpg",
    w: 568, h: 757,
    note: "Created in Maya, Bryce & Photoshop.",
  },
  {
    slug: "fathom-ii",
    title: "Fathom (II)",
    collection: "digital-art",
    image: "img/fathom-ii.jpg",
    w: 568, h: 757,
    note: "Created in Maya, Bryce & Photoshop.",
  },
  {
    slug: "gift",
    title: "Gift",
    collection: "digital-art",
    image: "img/gift.jpg",
    w: 568, h: 670,
    note: "Created in Maya & Photoshop.",
  },
  {
    slug: "imagine",
    title: "Imagine",
    collection: "digital-art",
    image: "img/imagine.jpg",
    w: 568, h: 904,
    note: "Created in Photoshop.",
  },
  {
    slug: "magic",
    title: "Magic",
    collection: "digital-art",
    image: "img/magic.jpg",
    w: 568, h: 758,
    note: "Created in Photoshop.",
  },
  {
    slug: "monolith",
    title: "Monolith",
    collection: "digital-art",
    image: "img/monolith.jpg",
    w: 568, h: 757,
    note: "Created in Maya, Bryce & Photoshop.",
  },
  {
    slug: "the-cave-where-az-dg",
    title: "The Cave Where AZ & DG",
    collection: "digital-art",
    image: "img/the-cave-where-az-dg.jpg",
    w: 760, h: 428,
    note: "Created in Photoshop, Maya & Bryce.\n\nCommissioned by the Sci-Fi Channel to promote ‘Tinman’, the miniseries.\nVisit the Infinite Oz Experience.",
  },
  {
    slug: "the-crypt-of-floating-caskets",
    title: "The Crypt of Floating Caskets",
    collection: "digital-art",
    image: "img/the-crypt-of-floating-caskets.jpg",
    w: 760, h: 428,
    note: "Created in Photoshop, Maya & Bryce.\n\nCommissioned by the Sci-Fi Channel to promote ‘Tinman’, the miniseries.\nVisit the Infinite Oz Experience.",
  },
  {
    slug: "the-future-is-bright",
    title: "The Future is Bright",
    collection: "digital-art",
    image: "img/the-future-is-bright.jpg",
    w: 568, h: 902,
    note: "Created in Photoshop. This was a concept produced for a Dublin based ad campaign. The brief was to address the concept that, though we are living in a damaged world, we may heal it through environmentally conscious behaviour.",
  },
  {
    slug: "the-gloaming-born",
    title: "The Gloaming Born",
    collection: "digital-art",
    image: "img/the-gloaming-born.jpg",
    w: 760, h: 426,
    note: "Created in Photoshop, from approximately 200 layers, using photographic and painted elements. It was designed as a mural for my daughter.",
  },
  {
    slug: "the-greenwood-deep",
    title: "The Greenwood Deep",
    collection: "digital-art",
    image: "img/the-greenwood-deep.jpg",
    w: 568, h: 790,
    note: "Created In Photoshop.",
  },
  {
    slug: "the-loom",
    title: "The Loom",
    collection: "digital-art",
    image: "img/the-loom.jpg",
    w: 568, h: 757,
    note: "Created using ZBrush & Photoshop.",
  },
  {
    slug: "the-moss-dragon-the-butterfly",
    title: "The Moss Dragon & The Butterfly",
    collection: "digital-art",
    image: "img/the-moss-dragon-the-butterfly.jpg",
    w: 760, h: 558,
    note: "Created in Photoshop, using a Wacom Tablet and my own macro shots.",
  },
  {
    slug: "the-twins",
    title: "The Twins",
    collection: "digital-art",
    image: "img/the-twins.jpg",
    w: 568, h: 511,
    note: "Created in Maya, Bryce & Photoshop.",
  },
  {
    slug: "the-wood-dragon-the-ladybird",
    title: "The Wood Dragon & The Ladybird",
    collection: "digital-art",
    image: "img/the-wood-dragon-the-ladybird.jpg",
    w: 760, h: 420,
    note: "Created in Photoshop, using a Wacom Tablet and my own macro shots.",
  },
  {
    slug: "the-wood-dragon-the-spiders-lair",
    title: "The Wood Dragon & The Spider’s Lair",
    collection: "digital-art",
    image: "img/the-wood-dragon-the-spiders-lair.jpg",
    w: 760, h: 425,
    note: "Created in Photoshop, using a Wacom Tablet and my own macro shots.",
  },
  {
    slug: "triptych",
    title: "Triptych",
    collection: "digital-art",
    image: "img/triptych.jpg",
    w: 568, h: 475,
    note: "Created using ZBrush & Photoshop.",
  },
  {
    slug: "wayland",
    title: "Wayland",
    collection: "digital-art",
    image: "img/wayland.jpg",
    w: 568, h: 568,
    note: "Created in Bryce & Photoshop.",
  },
  {
    slug: "wonder",
    title: "Wonder",
    collection: "digital-art",
    image: "img/wonder.jpg",
    w: 568, h: 863,
    note: "Created in Photoshop, using a Wacom Tablet & stock photography.",
  },
  {
    slug: "autumn-in-ravensdale",
    title: "Autumn in Ravensdale",
    collection: "photography",
    image: "img/autumn-in-ravensdale.jpg",
    w: 1400, h: 510,
    note: "Ravensdale Wood near Carlingford is one the most magical places I’ve ever been. I shot this a couple of years ago, the wood blazing in the golds and ambers of autumn.",
  },
  {
    slug: "benbulbin",
    title: "Benbulbin",
    collection: "photography",
    image: "img/benbulbin.jpg",
    w: 1500, h: 518,
  },
  {
    slug: "dragonfly",
    title: "Dragonfly",
    collection: "photography",
    image: "img/dragonfly.jpg",
    w: 1200, h: 700,
  },
  {
    slug: "forest-lake",
    title: "Forest Lake",
    collection: "photography",
    image: "img/forest-lake.jpg",
    w: 1400, h: 410,
  },
  {
    slug: "glencree-ii",
    title: "Glencree (II)",
    collection: "photography",
    image: "img/glencree-ii.jpg",
    w: 1500, h: 520,
  },
  {
    slug: "gleninchaquin-park",
    title: "Gleninchaquin Park",
    collection: "photography",
    image: "img/gleninchaquin-park.jpg",
    w: 1400, h: 499,
    note: "This was a view from high up in Gleninchaquin Forest Park - the park was hard to find, and at the end of a 5 mile dirt track, but was worth it! This shot is a crop of the original 15000 px panorama.",
  },
  {
    slug: "glowing-valley",
    title: "Glowing Valley",
    collection: "photography",
    image: "img/glowing-valley.jpg",
    w: 1500, h: 610,
  },
  {
    slug: "hillside",
    title: "Hillside",
    collection: "photography",
    image: "img/hillside.jpg",
    w: 1500, h: 809,
  },
  {
    slug: "ladys-view",
    title: "Lady’s View",
    collection: "photography",
    image: "img/ladys-view.jpg",
    w: 1400, h: 459,
    note: "Lday’s View is one of those classic tourist views - and for good reason. It is just a mindblowing place to stand. The Lakes of Killarney spread out into the distance through the forests and mountains of the National Park. This was one of the biggest panoramas I’ve ever created - around 40 individual 10MP photographs make up this view (it would print around 5 metres across in full resolution!).",
  },
  {
    slug: "lough-melvyn",
    title: "Lough Melvyn",
    collection: "photography",
    image: "img/lough-melvyn.jpg",
    w: 1500, h: 539,
  },
  {
    slug: "lough-teagh-panorama",
    title: "Lough Teagh Panorama (I)",
    collection: "photography",
    image: "img/lough-teagh-panorama.jpg",
    w: 1500, h: 442,
  },
  {
    slug: "lough-teagh-panorama1",
    title: "Lough Teagh Panorama (II)",
    collection: "photography",
    image: "img/lough-teagh-panorama1.jpg",
    w: 1500, h: 424,
  },
  {
    slug: "moss-stump",
    title: "Moss & Stump",
    collection: "photography",
    image: "img/moss-stump.jpg",
    w: 1000, h: 574,
    note: "Moss covered treestump.",
  },
  {
    slug: "mountaintop-puddle-i",
    title: "Mountaintop Puddle (I)",
    collection: "photography",
    image: "img/mountaintop-puddle-i.jpg",
    w: 1000, h: 1500,
  },
  {
    slug: "mountaintop-puddle-ii",
    title: "Mountaintop Puddle (II)",
    collection: "photography",
    image: "img/mountaintop-puddle-ii.jpg",
    w: 1000, h: 598,
    note: "Low angle shot of a puddle taken on mountaintop.",
  },
  {
    slug: "mushroom",
    title: "Mushroom",
    collection: "photography",
    image: "img/mushroom.jpg",
    w: 1000, h: 667,
  },
  {
    slug: "mushrooms",
    title: "Mushrooms",
    collection: "photography",
    image: "img/mushrooms.jpg",
    w: 1000, h: 1500,
  },
  {
    slug: "sun-through-trees",
    title: "Sun Through Trees",
    collection: "photography",
    image: "img/sun-through-trees.jpg",
    w: 1000, h: 1291,
    note: "Sunlight streams through trees.",
  },
  {
    slug: "sunlit-woods",
    title: "Sunlit Woods",
    collection: "photography",
    image: "img/sunlit-woods.jpg",
    w: 1500, h: 380,
    note: "Panorama taken in Lorem Ipsum woods. Click below for full image.",
  },
  {
    slug: "sunrise-at-castlemartyr",
    title: "Sunrise at Castlemartyr",
    collection: "photography",
    image: "img/sunrise-at-castlemartyr.jpg",
    w: 1200, h: 829,
    featured: true,
    note: "We stayed in Castlemartyr a couple of months back, and one morning I got up early for a walk. A thick mist was rolling over the landscape, and the sun was rising through it. I came down to the river and this was the sight which greeted me - just breathtaking!",
  },
  {
    slug: "the-black-valley",
    title: "The Black Valley",
    collection: "photography",
    image: "img/the-black-valley.jpg",
    w: 1400, h: 410,
    note: "Killarney is full of spectacular valleys, forests, hills and mountains - I caught this view towards dusk, looking down the Black Valley.",
  },
  {
    slug: "the-gap-of-dunloe",
    title: "The Gap of Dunloe",
    collection: "photography",
    image: "img/the-gap-of-dunloe.jpg",
    w: 1400, h: 586,
    note: "The Gap of Dunloe is a really special place, well worth a visit. This was another experiment, fusing around 35 photos together to create this panorama.",
  },
  {
    slug: "the-gap-of-dunloe-ii",
    title: "The Gap of Dunloe II",
    collection: "photography",
    image: "img/the-gap-of-dunloe-ii.jpg",
    w: 1400, h: 797,
    note: "The Gap of Dunloe is just a breathtaking place - we had a picnic on a rocky outcrop and watched the sun blaze down the valley. Original file is about 14000 px.",
  },
  {
    slug: "the-glen-of-aherloe",
    title: "The Glen of Aherloe",
    collection: "photography",
    image: "img/the-glen-of-aherloe.jpg",
    w: 1400, h: 572,
    note: "The entire valley was bursting with God Rays - absolutely amazing sight. This is a panorama of about 15 shots.",
  },
  {
    slug: "the-pass",
    title: "The Pass",
    collection: "photography",
    image: "img/the-pass.jpg",
    w: 1400, h: 488,
    note: "This landscape was epic in the true sense of the word. This is a crop from one corner of a 40 photo panorama - the previous day, we had driven up that windy road you see weaving all the way to up to Barley Lake (a ‘corrie’ lake which sits into the bowl you can see at the top).",
  },
  {
    slug: "tomies-wood",
    title: "Tomie’s Wood",
    collection: "photography",
    image: "img/tomies-wood.jpg",
    w: 1200, h: 886,
    featured: true,
    note: "Tomie’s Wood is a genuinely magical place. It is one of the few remaining slivers of the original primordal oak forest which once covered Ireland. I spent a few hours wandering through it and I think I took about 1000 photos! It was an astounding place and it was a privilige to explore it..",
  },
  {
    slug: "treestump-in-sunlight",
    title: "Treestump in Sunlight (II)",
    collection: "photography",
    image: "img/treestump-in-sunlight.jpg",
    w: 1000, h: 2269,
    note: "Treestump in Sunlight",
  },
  {
    slug: "treestump-in-sunlight1",
    title: "Treestump in Sunlight (I)",
    collection: "photography",
    image: "img/treestump-in-sunlight1.jpg",
    w: 1000, h: 1809,
    note: "Treestump in Sunlight.",
  },
];
